- hosts: 192.168.28.11
  vars:
    http_port: 80
    max_clients: 200
  remote_user: root
  tasks:
  - name: ensure apache is at the latest version
    command: yum install -y httpd
    command: systemctl start httpd
 
    #warn=False
    # #yum:
    # name: httpd
      #state: latest
      #  - name: write the apache config file
      #    template:
      #src: /srv/httpd.j2
      #      dest: /etc/httpd.conf
      #    notify:
      #    - restart apache
      #  - name: ensure apache is running
      #    service:
      #      name: httpd
      #      state: started
  handlers:
          #- name: restart apache
      #command: systemctl start httpd
      #service:
      # name: httpd
      # state: restarted
